spring:

  http:
    encoding:
      force: true

    # 文件上传限制
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  # thymeleaf框架
  thymeleaf:
    mode: LEGACYHTML5

  # JPA框架
  jpa:
    open-in-view: true # 多对多关系相互引用中，需要让session在相应过程中保持开启状态，懒加载用到
    show-sql: false # 不显示sql
    hibernate:
        ddl-auto: update # 设置变动了则改变表结构

  # 数据源
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.29.231.216:3306/funny?useUnicode=yes&characterEncoding=UTF8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

server:
  port: 80 # 设置默认端口


weixin:
  appid: wxa372cd2ec12c7da3
  secret: 85e2da2396717ba178f4c874e20b6ffd
  noncestr: HelloWorld
  user: hsywp888
  pwd: ytxjr001


qiniu:
  accessKey: HpHWLi6wgCGI2Lpvd1KCk2HFcLWyY285kAICX3AK
  secretKey: BbeeH_tY306aanajadMgfUaYgaMve7xQzzC3H3Be
  bucketName: zhangqinghua
  basePath: http://owqrqmr2h.bkt.clouddn.com

###七牛云的key
#qiniu.accessKey=
#qiniu.=
#qiniu.bucketName=zhangqinghua
#qiniu.basePath=http://owqrqmr2h.bkt.clouddn.com
### 文件上传相关
#file_url=http://owqrqmr2h.bkt.clouddn.com